spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unique?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 9527root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver